### ISSUE TITLE
Smart Call Home improvements

### ISSUE THREAD

**Issue by guilhemmarchand** [inspired/cisco_ios#4]
Hi,

The "inventory_device" view references a lookup table called "Cisco_Device" which is not available anywhere in the App or the Addon.

cisco_ios/default/data/ui/views/inventory_device.xml

```
    <searchString>| inputlookup Cisco_Device | search host=$form.host$ | fields host | appendcols [search eventtype=cisco_ios-smart_call_home host=$form.host$ | rename hostname AS host | fields host | head 1]</searchString>
```

Splunk will return the following error as the lookup table does not exist: "The lookup table 'Cisco_Device' is invalid."

Is that expected ? Does this lookup table comes from an external App that should be installed ? 
I couldn't find that in your docs.

Thank you.

Guilhem

**Comment by inspired** [comment]
It's unfinished code, really. I'm looking at removing this functionality since it's very flaky. Smart Call Home is not the best way to get inventory data. I would much rather see some kind of inventory framework built into Splunk that we can use across apps. 

The referenced lookup was previously generated by a saved search.

What do you suggest? Remove it completely? Smart Call Home isn't even working on Catalyst 2960 switches, the most deployed Enterprise switch worldwide, since they don't support scheduling. Enabling this on a 2960 will generate ONE Smart Call Home event, not periodically, so it can't be relied on for inventory.

**Comment by guilhemmarchand** [comment]
Hi,

No, i don't suggest removing the Smart Call Home service :-)
I just was reporting the error due to an non existing lookup table.

The Smart Call Home service is a very cool idea, and a very very rich source of data.
We are currently testing it, for now essentially with NX/OS devices, but we will also test it with our IOS devices.

I understand the Catalyst 2960 limitation (i would have thought the most common Catalyst device would have been some 37x families), therefore even if this is the most deployed device, this is as far is a know absolutely not the future of Cisco networking devices, and NX/OS has this feature working perfectly.

Definitively i wouldn't suggest removing it :+1:

**Comment by inspired** [comment]
Thanks for your input. If we focus on keeping SCH supported, the things on my road-map are:
- KV store collection for Inventory
- Saved search that adds the latest inventory events into the KV store
- Better use of the inventory data throughout the app

**Comment by inspired** [comment]
Decided to remove SCH all together
